#server config
server:
  port: 8080

#datasource
spring:
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: c##bumtt
    password: bumtt

  #oauth2 naver config
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: Naver
            client-id: VgHUGvAVfUVMZV49SAKE
            client-secret: AJULSSI5sG
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - birthyear
              - mobile

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

#mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml

#s3
cloud:
  aws:
    s3:
      bucket: bumtt-s3-1
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIAYS2NVIL5QOKDKFFR
      secret-key: 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
#jasypt:
#  encryptor:
#    bean: jasyptStringEncryptor
#    key: ${key}

