#server config
#server:
#  port: 8080

#datasource
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: C##BUMTT
    password: BUMTT

#mybatis config
mybatis:
  mapper-locations: mappers/**.xml
